services:
  - type: web
    name: udicti-cli
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FIREBASE_CONFIG_JSON
        sync: false  # Set this manually in Render dashboard
      - key: PORT
        value: "10000"
    healthCheckPath: /health
    scaling:
      minInstances: 1
      maxInstances: 3