[project]
name = "udicti-cli"
version = "1.0.0"
description = "A powerful CLI tool to simplify your workflow"
authors = [
  { name="Siriily", email="siriily@example.com" },
]
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.11"
dependencies = [
    "click>=8.1",
    "rich",
    "pyfiglet",
    "typer[all]",
    "requests",
    "firebase-admin",
    "httpx",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff",
]

[project.scripts]
udicti = "udicti_cli.main:app" 

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 88

[tool.black]
line-length = 88
