name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest flake8 black
    
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 packages/cli/udicti_cli --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 packages/cli/udicti_cli --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Check code formatting with black
      run: |
        black --check packages/cli/udicti_cli --line-length=88
    
    - name: Test CLI functionality
      run: |
        udicti --help
        udicti welcome || echo "Welcome command needs Firebase config"
    
    - name: Test package build
      run: |
        pip install build
        python -m build
        pip install dist/*.whl
        udicti --version || udicti --help

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
    
    - name: Check dependencies for vulnerabilities
      run: |
        safety check --file requirements.txt || echo "No requirements.txt found"
        pip freeze | safety check --stdin
    
    - name: Run security linter
      run: |
        bandit -r packages/cli/udicti_cli -f json || echo "Security scan completed"